In [3]:
import peforth
peforth.dictate(r'''
\ Now we redefine the 'unknown' command that was do-nothing by default
: unknown ( token -- thing Y|N) // Try to find the unknown token in __main__
  py> getattr(sys.modules['__main__'],pop(),"Ûnknôwn") 
  py> str(tos())=="Ûnknôwn" if drop false else true then ;
  /// here after, when FORTH come accross an unknown token, instead of alerting 
  /// it try to find the token in python __main__ module name space.

\ Redefine \ command to print the comment line
code \ print(nexttoken('\n')) end-code 
''');


reDef unknown
reDef \


In [2]:
?slice


In [ ]:
%load 

In [4]:
cols = "abc"
ind = range(3)
data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
data

{'a': ['a0', 'a1', 'a2'], 'b': ['b0', 'b1', 'b2'], 'c': ['c0', 'c1', 'c2']}

In [5]:
{c:11 for c in cols}

{'a': 11, 'b': 11, 'c': 11}

In [15]:
%f <py> {c for c in "abc"} </pyV> tib.
%f <py> [c for c in "abc"] </pyV> tib.
%f <py> (c for c in "abc") </pyV> tib.
%f <py> (c for c in "abc") </pyV> py> list(pop()) tib.



<py> {c for c in "abc"} </pyV> tib. \ ==> {'b', 'a', 'c'} (<class 'set'>)
<py> [c for c in "abc"] </pyV> tib. \ ==> ['a', 'b', 'c'] (<class 'list'>)
<py> (c for c in "abc") </pyV> tib. \ ==> <generator object compyle_anonymous.<locals>.<genexpr> at 0x000001E8DC926048> (<class 'generator'>)
<py> (c for c in "abc") </pyV> py> list(pop()) tib. \ ==> ['a', 'b', 'c'] (<class 'list'>)


In [1]:
import numpy as np

In [16]:
x = [12,34]
%f x . cr
[x]

[12, 34]


[[12, 34]]

In [39]:
x = np.array([12,34])
x
[x[:,np.newaxis], [91,92]]
x[:,np.newaxis][:,np.newaxis]
x[:,np.newaxis][:,np.newaxis][:,np.newaxis]
%f \ --------------------------
[x]


array([12, 34])

[array([[12],
        [34]]), [91, 92]]

array([[[12]],

       [[34]]])

array([[[[12]]],


       [[[34]]]])

--------------------------


[array([12, 34])]

In [34]:
x = [12,34]
x
x[:,np.newaxis]
x[:,np.newaxis][:,np.newaxis]
x[:,np.newaxis][:,np.newaxis][:,np.newaxis]

[12, 34]

TypeError: list indices must be integers or slices, not tuple